using System;

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    https://projecteuler.net/problem=2  */


namespace NetEuler
{
    static class EvenFib
    {
        public static void Solve()
        {
            int j = 1;
            int temp = 0;
            int sum = 0;
            for (int i = 2; i <= 4000000; i += temp)
            {
                if(i % 2 == 0){
                    sum += i;
                }
                temp = j;
                j = i;

            }
            Console.WriteLine("Solution: {0}", sum);
        }
    }
}